'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CreateAgreement
    
    '''<summary>
    '''CreateAgreement_Result control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_Result As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''CreateAgreement_AgreementNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_AgreementNumber As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_Cabling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_Cabling As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''CreateAgreement_CablingQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_CablingQty As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_CablingValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_CablingValue As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_Points control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_Points As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''CreateAgreement_PointsQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_PointsQty As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_PointsValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_PointsValue As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_Sundries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_Sundries As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''CreateAgreement_SundriesQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_SundriesQty As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_SundriesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_SundriesValue As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_OpeningCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_OpeningCharge As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_StartChargesFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_StartChargesFrom As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_InitFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_InitFrequency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnRecalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRecalculate As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''CreateAgreement_InitRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_InitRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_NumPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_NumPayments As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''CreateAgreement_FollowOnFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_FollowOnFrequency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CreateAgreement_FollowOnRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateAgreement_FollowOnRate As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnCaptureCardDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCaptureCardDetails As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnCreateAgreement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateAgreement As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnGoBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoBack As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
