'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewEnquiry
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''InfoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''EnquiryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryTitle As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EnquiryForename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryForename As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquirySurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquirySurname As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryAddress1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryAddress2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryAddress3 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryAddress4 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryAddress5 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryPostcode As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryTel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryTel1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryTel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryTel2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnLoadDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadDays As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''AvailableDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvailableDays As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EnquiryEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryEmail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''EnquiryPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryPassword As Global.System.Web.UI.HtmlControls.HtmlInputPassword
    
    '''<summary>
    '''EnquiryMainText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnquiryMainText As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
